FROM node:slim as build

WORKDIR /usr/src/app

COPY package*.json .

RUN --mount=type=cache,target=/root/.npm npm install

COPY . .

RUN [ "npm", "run", "build" ]

FROM nginxinc/nginx-unprivileged

COPY --from=build /usr/src/app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

