services:

  nginx:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    networks:
      - expense-network
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          memory: 256m

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=postgres-db
    networks:
      - expense-network
    depends_on:
      migrate:
         condition: service_completed_successfully
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m

  migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=postgres-db
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - expense-network
    command: python manage.py migrate
    restart: "no"

  postgres-db:
    image: postgres:16
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 45s
    networks:
      - expense-network
    restart: unless-stopped

networks:
  expense-network:

volumes:
  postgres_data: